# BUILD to  registry.cn-beijing.aliyuncs.com/imanager/ubuntu_aigislib_cpu
FROM nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04

RUN rm /etc/apt/sources.list.d/* && \
 apt-get update && \
 apt-get install -y make gcc binutils perl libx11-dev xinit libgomp1 libxtst6 libxi6 language-pack-zh-hans lsb-core && \
 apt-get install -y libc6-i386 libglu1-mesa libxcursor1 && \
 apt-get install -y curl unzip libaio1 && \
 apt-get install -y vim-gtk && \
 apt-get install -y mysql-client mongodb-clients && \
 apt-get clean && apt-get autoclean && \
 rm -rf /var/lib/apt/lists/* && \
 curl -LO http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
 bash Miniconda3-latest-Linux-x86_64.sh -p /miniconda -b && \
 rm Miniconda3-latest-Linux-x86_64.sh

ENV PATH=/miniconda/bin:${PATH}
# RUN conda update -y conda

WORKDIR /home/supermap

COPY requirements-conda-gpu.yml ./

RUN conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/ && \
  conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/ && \
  conda config --set show_channel_urls yes && \
  conda env update -n base -f requirements-conda-gpu.yml && \
  conda clean --all -f -y
